[package]
name = "light-macros"
version = "0.1.0"
edition = "2021"
description = "Set of proc-macros used in Light Protocol"
license = "Apache-2.0"

[dependencies]
bs58 = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[lib]
proc-macro = true
